### ISSUE TITLE
Allow both `bind:value` and an `onChange` handler on the same element

### ISSUE THREAD

**Issue by mcav** [adobe/babel-plugin-transform-react-twist#6]
Torq-intl defines this:

```jsx
<select bind:value={ this.locale } onChange={ () => this.updateLocale() }> ... </select>
```

I think we should allow it. Right now, we emit a warning about using both attributes and abort creating the two-way binding, which means this doesn't work. Callbacks can be used for things unrelated to the bound value, so I think we should just emit the warning (if at all) and set up the two-way binding regardless.

**Comment by lanther** [comment]
Yeah, I agree - good point!
